### ISSUE TITLE
Are you planning on publishing this app to Apple Store?

### ISSUE THREAD

**Issue by balldk** [richie-south/ultimate_pi#1]
I used to use android and absolutely love your app, but I've switched to ios recently, which doesn't support ultimate pi. I miss it to be honest, and there's no ios app out there have the same idea as yours. I hope this app would available on ios one day

**Comment by richie-south** [comment]
Hey, Thanks for the kind words!
I also missed it when I switched to iOS so I actually made an  iOS version BUT i only released it as a beta so only i could use it. This because I wanted to improve some parts of it and rewrite the code, but once i hade it i sort of forgot about it. 

Currently traveling for a few more months and don't have access to any computer but I can release a version for iOS early next year if you are still interested by then 😊
